> install.packages("igraph")
> library(igraph)
> getwd()
> nodes <- read.csv("nodes.csv")
> head(nodes)
> links <- read.csv("edges.csv")
> View(links)
> head(links)
> net <- graph.data.frame(d=links, vertices=nodes, directed=T)
> m=as.matrix(net)
> get.adjacency(m)
> plot(net)